import React, { useCallback, useRef, useState } from 'react';
import { Alert, FlatList, Platform, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useSettings } from '@/context/SettingsContext';
import { useTraining } from '@/context/TrainingContext';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { SetupModal } from '@/components/SetupModal';
import { LapRow } from '@/components/LapRow';
import { SessionConfig } from '@/types/training';
import { formatTime, calculateStats } from '@/utils/calculations';
import { saveSession } from '@/utils/storage';

export default function CronometroScreen() {
  const colors=useColors(), insets=useSafeAreaInsets(), {settings}=useSettings();
  const {timerState,elapsed,currentLapTime,laps,sessionConfig,start,pause,resume,addLap,finish,reset}=useTraining();
  const [showSetup,setShowSetup]=useState(false); const lapListRef=useRef<FlatList>(null);
  const isIdle=timerState==='idle',isRunning=timerState==='running',isPaused=timerState==='paused',isFinished=timerState==='finished',isActive=isRunning||isPaused;
  const stats=calculateStats(laps,sessionConfig.distancePerLap,sessionConfig.targetLapTimeMs); const webTop=Platform.OS==='web'?67:0; const bottomNavSpace=Platform.OS==='web'?92:Math.max(insets.bottom,10)+72;
  const handleStart=useCallback((config:SessionConfig)=>{setShowSetup(false);start(config);Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy)},[start]);
  const handleLap=useCallback(()=>{addLap();Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);setTimeout(()=>{try{lapListRef.current?.scrollToIndex({index:0,animated:true})}catch{}},100)},[addLap]);
  const handlePause=useCallback(()=>{pause();Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)},[pause]); const handleResume=useCallback(()=>{resume();Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)},[resume]);
  const doFinish=useCallback(async()=>{const result=finish();if(!result)return;if(result.laps.length)await saveSession({id:Date.now().toString()+Math.random().toString(36).substring(2,8),date:new Date().toISOString(),athleteName:sessionConfig.athleteName,trainingType:sessionConfig.trainingType,distancePerLap:sessionConfig.distancePerLap,targetLapTimeMs:sessionConfig.targetLapTimeMs,laps:result.laps,totalTime:result.totalTime});Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)},[finish,sessionConfig]);
  const handleFinish=useCallback(()=>Alert.alert('Finalizar','¿Terminar el entrenamiento?',[{text:'Cancelar',style:'cancel'},{text:'Finalizar',style:'destructive',onPress:doFinish}]),[doFinish]);

  return <View style={[styles.container,{backgroundColor:colors.background,paddingTop:webTop}]}>
    <View style={[styles.timerZone,{paddingTop:isActive?insets.top+10:insets.top+36}]}>{isActive&&<Text style={[styles.sessionMeta,{color:colors.mutedForeground}]}>{sessionConfig.athleteName||'Sin nombre'} · {sessionConfig.trainingType}{sessionConfig.distancePerLap>0?` · ${sessionConfig.distancePerLap}m`:''}{sessionConfig.targetLapTimeMs?` · Obj. ${formatTime(sessionConfig.targetLapTimeMs)}`:''}</Text>}{isFinished?<View style={styles.finishedZone}><Ionicons name="checkmark-circle" size={58} color={colors.success}/><Text style={[styles.finishedTitle,{color:colors.foreground}]}>¡Completado!</Text><Text style={[styles.finishedSub,{color:colors.mutedForeground}]}>{laps.length} vuelta{laps.length!==1?'s':''} · {formatTime(elapsed)}</Text>{stats.bestLap&&<Text style={[styles.prTxt,{color:colors.lapBest}]}>Mejor vuelta: {formatTime(stats.bestLap.lapTime)}</Text>}</View>:<><Text style={[styles.timer,{color:colors.timerDisplay}]}>{formatTime(elapsed)}</Text>{isActive&&<View style={styles.lapInfoRow}><Text style={[styles.lapLabel,{color:colors.mutedForeground}]}>VUELTA {laps.length+1}</Text><Text style={[styles.lapClock,{color:colors.primary}]}>{formatTime(currentLapTime)}</Text></View>}{isIdle&&<Text style={[styles.idleHint,{color:colors.mutedForeground}]}>Cronómetro de alta precisión</Text>}</>}</View>
    {laps.length>0&&isActive&&stats.bestLap&&<View style={[styles.strip,{backgroundColor:colors.card,borderColor:colors.border}]}><StripChip label="Mejor" value={formatTime(stats.bestLap.lapTime)} color={colors.lapBest} colors={colors}/><View style={[styles.div,{backgroundColor:colors.border}]}/><StripChip label="Promedio" value={formatTime(stats.averageLapTime)} color={colors.foreground} colors={colors}/><View style={[styles.div,{backgroundColor:colors.border}]}/><StripChip label="Consist." value={`${stats.consistency.toFixed(1)}%`} color={colors.mutedForeground} colors={colors}/>{stats.averageSpeed>0&&<><View style={[styles.div,{backgroundColor:colors.border}]}/><StripChip label="Vel. med." value={`${stats.averageSpeed.toFixed(1)}`} color={colors.primary} colors={colors}/></>}</View>}
    {laps.length>0&&<View style={styles.lapsSection}><View style={[styles.lapsHead,{borderBottomColor:colors.border}]}><Text style={[styles.lhTxt,{color:colors.mutedForeground,width:34}]}>V</Text><Text style={[styles.lhTxt,{color:colors.mutedForeground,flex:1}]}>Vuelta</Text><Text style={[styles.lhTxt,{color:colors.mutedForeground,width:76,textAlign:'right'}]}>Total</Text>{sessionConfig.distancePerLap>0&&<Text style={[styles.lhTxt,{color:colors.mutedForeground,width:68,textAlign:'right'}]}>Vel.</Text>}<Text style={[styles.lhTxt,{color:colors.mutedForeground,width:68,textAlign:'right'}]}>{sessionConfig.targetLapTimeMs?'Objetivo':'Δ'}</Text></View><FlatList ref={lapListRef} data={[...laps].reverse()} keyExtractor={i=>String(i.number)} renderItem={({item})=><LapRow lap={item} isBest={item.number===stats.bestLap?.number} isWorst={item.number===stats.worstLap?.number} distancePerLap={sessionConfig.distancePerLap} avgLapTime={stats.averageLapTime} targetLapTimeMs={sessionConfig.targetLapTimeMs}/>} showsVerticalScrollIndicator={false}/></View>}
    <View style={[styles.btns,{paddingBottom:bottomNavSpace}]}>{isIdle&&<TouchableOpacity style={[styles.bigBtn,{backgroundColor:colors.primary}]} onPress={()=>setShowSetup(true)}><Ionicons name="play" size={23} color={colors.primaryForeground}/><Text style={[styles.bigBtnTxt,{color:colors.primaryForeground}]}>Nuevo entrenamiento</Text></TouchableOpacity>}{isRunning&&<View style={styles.actionRow}><TouchableOpacity style={[styles.lapBtn,{backgroundColor:colors.card,borderColor:colors.primary}]} onPress={handleLap}><Ionicons name="flag" size={24} color={colors.primary}/><Text style={[styles.actionTxt,{color:colors.primary}]}>Vuelta</Text></TouchableOpacity><View style={styles.sideStack}><TouchableOpacity style={[styles.sideBtn,{backgroundColor:colors.secondary}]} onPress={handlePause}><Ionicons name="pause" size={22} color={colors.foreground}/></TouchableOpacity><TouchableOpacity style={[styles.sideBtn,{backgroundColor:`${colors.destructive}22`}]} onPress={handleFinish}><Ionicons name="stop" size={22} color={colors.destructive}/></TouchableOpacity></View></View>}{isPaused&&<View style={styles.pausedRow}><TouchableOpacity style={[styles.halfBtn,{backgroundColor:colors.primary}]} onPress={handleResume}><Ionicons name="play" size={22} color={colors.primaryForeground}/><Text style={[styles.actionTxt,{color:colors.primaryForeground}]}>Continuar</Text></TouchableOpacity><TouchableOpacity style={[styles.halfBtn,{backgroundColor:colors.destructive}]} onPress={handleFinish}><Ionicons name="stop" size={22} color="#fff"/><Text style={[styles.actionTxt,{color:'#fff'}]}>Finalizar</Text></TouchableOpacity></View>}{isFinished&&<TouchableOpacity style={[styles.bigBtn,{backgroundColor:colors.primary}]} onPress={()=>{reset();setShowSetup(true)}}><Ionicons name="refresh" size={22} color={colors.primaryForeground}/><Text style={[styles.bigBtnTxt,{color:colors.primaryForeground}]}>Nuevo entrenamiento</Text></TouchableOpacity>}</View>
    <SetupModal visible={showSetup} onClose={()=>setShowSetup(false)} onStart={handleStart} defaults={{athleteName:settings.athleteName,trainingType:settings.defaultTrainingType,distancePerLap:settings.defaultDistancePerLap}}/>
  </View>
}
function StripChip({label,value,color,colors}:any){return <View style={styles.chipItem}><Text style={[styles.chipVal,{color}]}>{value}</Text><Text style={[styles.chipLbl,{color:colors.mutedForeground}]}>{label}</Text></View>}
const styles=StyleSheet.create({container:{flex:1},timerZone:{alignItems:'center',paddingHorizontal:20,paddingBottom:10},sessionMeta:{fontSize:12,fontFamily:'Inter_500Medium',marginBottom:5},timer:{fontSize:56,fontFamily:'Inter_700Bold',letterSpacing:-2,fontVariant:['tabular-nums']},lapInfoRow:{alignItems:'center',marginTop:6,gap:1},lapLabel:{fontSize:10,fontFamily:'Inter_600SemiBold',letterSpacing:1.2},lapClock:{fontSize:23,fontFamily:'Inter_600SemiBold',fontVariant:['tabular-nums']},idleHint:{fontSize:14,fontFamily:'Inter_400Regular',marginTop:5},finishedZone:{alignItems:'center',gap:7,paddingVertical:6},finishedTitle:{fontSize:22,fontFamily:'Inter_700Bold'},finishedSub:{fontSize:15,fontFamily:'Inter_400Regular'},prTxt:{fontSize:13,fontFamily:'Inter_500Medium'},strip:{flexDirection:'row',alignItems:'center',marginHorizontal:14,borderRadius:12,padding:9,borderWidth:StyleSheet.hairlineWidth,marginBottom:8},chipItem:{flex:1,alignItems:'center',gap:2},chipVal:{fontSize:13,fontFamily:'Inter_600SemiBold',fontVariant:['tabular-nums']},chipLbl:{fontSize:9,fontFamily:'Inter_400Regular'},div:{width:1,height:26},lapsSection:{flex:1},lapsHead:{flexDirection:'row',paddingHorizontal:16,paddingVertical:7,borderBottomWidth:StyleSheet.hairlineWidth,gap:8},lhTxt:{fontSize:10,fontFamily:'Inter_600SemiBold',letterSpacing:.5},btns:{paddingHorizontal:14,paddingTop:8,gap:8},bigBtn:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,paddingVertical:16,borderRadius:14},bigBtnTxt:{fontSize:17,fontFamily:'Inter_700Bold'},actionRow:{flexDirection:'row',gap:10},lapBtn:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,minHeight:104,borderRadius:16,borderWidth:2},sideStack:{gap:8},sideBtn:{width:58,height:48,borderRadius:14,alignItems:'center',justifyContent:'center'},pausedRow:{flexDirection:'row',gap:10},halfBtn:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingVertical:16,borderRadius:14},actionTxt:{fontSize:16,fontFamily:'Inter_700Bold'}});
