import React,{useCallback,useRef,useState}from'react';
import{Alert,FlatList,Platform,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{useColors}from'@/hooks/useColors';
import{useSettings}from'@/context/SettingsContext';
import{useTraining}from'@/context/TrainingContext';
import{Ionicons}from'@expo/vector-icons';
import*as Haptics from'expo-haptics';
import{SetupModal}from'@/components/SetupModal';
import{LapRow}from'@/components/LapRow';
import{Lap,SessionConfig}from'@/types/training';
import{formatTime,calculateStats,isLapOnTarget}from'@/utils/calculations';
import{saveSession}from'@/utils/storage';

export default function CronometroScreen(){
 const c=useColors(),insets=useSafeAreaInsets(),{settings}=useSettings();
 const{timerState,elapsed,currentLapTime,laps,sessionConfig,start,pause,resume,addLap,finish,reset}=useTraining();
 const[showSetup,setShowSetup]=useState(false);const list=useRef<FlatList>(null);
 const idle=timerState==='idle',running=timerState==='running',paused=timerState==='paused',finished=timerState==='finished',active=running||paused;
 const timeTarget=sessionConfig.targetLapTimeMs,lapTarget=sessionConfig.targetLapCount,hasTime=!!timeTarget&&timeTarget>0,hasVolume=!!lapTarget&&lapTarget>0;
 const onTime=hasTime?currentLapTime<=timeTarget!:false,delta=hasTime?currentLapTime-timeTarget!:0,stats=calculateStats(laps,sessionConfig.distancePerLap,timeTarget);
 const misses=hasTime?laps.length-stats.lapsOnTarget:0,volumePct=hasVolume?Math.min(100,laps.length/lapTarget!*100):0,remaining=hasVolume?Math.max(0,lapTarget!-laps.length):0,volumeDone=hasVolume&&laps.length>=lapTarget!;
 const bottom=Platform.OS==='web'?92:Math.max(insets.bottom,10)+72,webTop=Platform.OS==='web'?67:0;
 const handleStart=useCallback((cfg:SessionConfig)=>{setShowSetup(false);start(cfg);Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy)},[start]);
 const handleLap=useCallback(()=>{addLap();Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);setTimeout(()=>{try{list.current?.scrollToIndex({index:0,animated:true})}catch{}},100)},[addLap]);
 const doFinish=useCallback(async()=>{const r=finish();if(!r)return;if(r.laps.length)await saveSession({id:Date.now().toString()+Math.random().toString(36).slice(2,8),date:new Date().toISOString(),athleteName:sessionConfig.athleteName,trainingType:sessionConfig.trainingType,distancePerLap:sessionConfig.distancePerLap,targetLapTimeMs:sessionConfig.targetLapTimeMs,targetLapCount:sessionConfig.targetLapCount,laps:r.laps,totalTime:r.totalTime});Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)},[finish,sessionConfig]);
 const handleFinish=useCallback(()=>{const extra=hasVolume&&!volumeDone?`\n\nLleva ${laps.length} de ${lapTarget} vueltas (${Math.round(volumePct)}%).`:'';Alert.alert('Finalizar',`¿Terminar el entrenamiento?${extra}`,[{text:'Cancelar',style:'cancel'},{text:'Finalizar',style:'destructive',onPress:doFinish}])},[doFinish,hasVolume,volumeDone,laps.length,lapTarget,volumePct]);
 const statusColor=onTime?c.lapBest:c.lapWorst;
 return <View style={[s.container,{backgroundColor:c.background,paddingTop:webTop}]}>
  <View style={[s.timerZone,{paddingTop:active?insets.top+8:insets.top+36}]}>
   {active&&<Text style={[s.meta,{color:c.mutedForeground}]} numberOfLines={1}>{sessionConfig.athleteName||'Sin nombre'} · {sessionConfig.trainingType}{sessionConfig.distancePerLap>0?` · ${sessionConfig.distancePerLap}m`:''}</Text>}
   {finished?<View style={s.finished}><Ionicons name="checkmark-circle" size={54} color={c.success}/><Text style={[s.done,{color:c.foreground}]}>¡Completado!</Text><Text style={[s.sub,{color:c.mutedForeground}]}>{hasVolume?`${laps.length}/${lapTarget} vueltas`:`${laps.length} vueltas`} · {formatTime(elapsed)}</Text>{hasVolume&&<Text style={[s.volumeDone,{color:volumeDone?c.lapBest:c.lapWorst}]}>{volumeDone?'Volumen cumplido':`${Math.round(volumePct)}% del volumen`}</Text>}{stats.bestLap&&<Text style={{color:c.lapBest}}>Mejor vuelta: {formatTime(stats.bestLap.lapTime)}</Text>}</View>:<><Text style={[s.timer,{color:c.timerDisplay}]}>{formatTime(elapsed)}</Text>{active&&(hasTime?<View style={[s.targetBox,{backgroundColor:`${statusColor}16`,borderColor:`${statusColor}55`}]}><View style={s.targetHead}><Text style={[s.label,{color:c.mutedForeground}]}>VUELTA {laps.length+1}</Text><View style={[s.pill,{backgroundColor:`${statusColor}22`}]}><Ionicons name={onTime?'checkmark-circle':'alert-circle'} size={13} color={statusColor}/><Text style={[s.pillTxt,{color:statusColor}]}>{onTime?'EN OBJETIVO':'SOBRE OBJETIVO'}</Text></View></View><Text style={[s.lapClockBig,{color:statusColor}]}>{formatTime(currentLapTime)}</Text><Text style={[s.delta,{color:statusColor}]}>{onTime?'Margen':'Exceso'} {(Math.abs(delta)/1000).toFixed(2)}s · Objetivo {formatTime(timeTarget!)}</Text></View>:<View style={s.lapInfo}><Text style={[s.label,{color:c.mutedForeground}]}>VUELTA {laps.length+1}</Text><Text style={[s.lapClock,{color:c.primary}]}>{formatTime(currentLapTime)}</Text></View>)}{idle&&<Text style={[s.hint,{color:c.mutedForeground}]}>Cronómetro de alta precisión</Text>}</>}
  </View>
  {active&&hasVolume&&<Volume actual={laps.length} target={lapTarget!} pct={volumePct} remaining={remaining} done={volumeDone} colors={c}/>} 
  {active&&hasTime&&<Coach laps={laps} target={timeTarget!} ok={stats.lapsOnTarget} fail={misses} pct={stats.targetCompliance} colors={c}/>} 
  {laps.length>0&&active&&stats.bestLap&&<View style={[s.strip,{backgroundColor:c.card,borderColor:c.border}]}><Chip label="Mejor" value={formatTime(stats.bestLap.lapTime)} color={c.lapBest} colors={c}/><View style={[s.div,{backgroundColor:c.border}]}/><Chip label="Promedio" value={formatTime(stats.averageLapTime)} color={c.foreground} colors={c}/><View style={[s.div,{backgroundColor:c.border}]}/><Chip label="Consist." value={`${stats.consistency.toFixed(1)}%`} color={c.mutedForeground} colors={c}/>{stats.averageSpeed>0&&<><View style={[s.div,{backgroundColor:c.border}]}/><Chip label="Vel. med." value={stats.averageSpeed.toFixed(1)} color={c.primary} colors={c}/></>}</View>}
  {laps.length>0&&<View style={s.laps}><View style={[s.lapsHead,{borderBottomColor:c.border}]}><Text style={[s.th,{color:c.mutedForeground,width:34}]}>V</Text><Text style={[s.th,{color:c.mutedForeground,flex:1}]}>Vuelta</Text><Text style={[s.th,{color:c.mutedForeground,width:76,textAlign:'right'}]}>Total</Text>{sessionConfig.distancePerLap>0&&<Text style={[s.th,{color:c.mutedForeground,width:68,textAlign:'right'}]}>Vel.</Text>}<Text style={[s.th,{color:c.mutedForeground,width:68,textAlign:'right'}]}>{hasTime?'Objetivo':'Δ'}</Text></View><FlatList ref={list} data={[...laps].reverse()} keyExtractor={x=>String(x.number)} renderItem={({item})=><LapRow lap={item} isBest={item.number===stats.bestLap?.number} isWorst={item.number===stats.worstLap?.number} distancePerLap={sessionConfig.distancePerLap} avgLapTime={stats.averageLapTime} targetLapTimeMs={timeTarget}/>} showsVerticalScrollIndicator={false}/></View>}
  <View style={[s.btns,{paddingBottom:bottom}]}>{idle&&<TouchableOpacity style={[s.bigBtn,{backgroundColor:c.primary}]} onPress={()=>setShowSetup(true)}><Ionicons name="play" size={23} color={c.primaryForeground}/><Text style={[s.bigTxt,{color:c.primaryForeground}]}>Nuevo entrenamiento</Text></TouchableOpacity>}{running&&<View style={s.action}><TouchableOpacity style={[s.lapBtn,{backgroundColor:c.card,borderColor:c.primary}]} onPress={handleLap}><Ionicons name="flag" size={24} color={c.primary}/><Text style={[s.actionTxt,{color:c.primary}]}>Vuelta</Text></TouchableOpacity><View style={s.stack}><TouchableOpacity style={[s.side,{backgroundColor:c.secondary}]} onPress={()=>pause()}><Ionicons name="pause" size={22} color={c.foreground}/></TouchableOpacity><TouchableOpacity style={[s.side,{backgroundColor:`${c.destructive}22`}]} onPress={handleFinish}><Ionicons name="stop" size={22} color={c.destructive}/></TouchableOpacity></View></View>}{paused&&<View style={s.action}><TouchableOpacity style={[s.half,{backgroundColor:c.primary}]} onPress={()=>resume()}><Ionicons name="play" size={22} color={c.primaryForeground}/><Text style={[s.actionTxt,{color:c.primaryForeground}]}>Continuar</Text></TouchableOpacity><TouchableOpacity style={[s.half,{backgroundColor:c.destructive}]} onPress={handleFinish}><Ionicons name="stop" size={22} color="#fff"/><Text style={[s.actionTxt,{color:'#fff'}]}>Finalizar</Text></TouchableOpacity></View>}{finished&&<TouchableOpacity style={[s.bigBtn,{backgroundColor:c.primary}]} onPress={()=>{reset();setShowSetup(true)}}><Ionicons name="refresh" size={22} color={c.primaryForeground}/><Text style={[s.bigTxt,{color:c.primaryForeground}]}>Nuevo entrenamiento</Text></TouchableOpacity>}</View>
  <SetupModal visible={showSetup} onClose={()=>setShowSetup(false)} onStart={handleStart} defaults={{athleteName:settings.athleteName,trainingType:settings.defaultTrainingType,distancePerLap:settings.defaultDistancePerLap}}/>
 </View>
}
function Volume({actual,target,pct,remaining,done,colors}:{actual:number;target:number;pct:number;remaining:number;done:boolean;colors:ReturnType<typeof useColors>}){const color=done?colors.lapBest:colors.primary;return <View style={[s.panel,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={s.panelHead}><View><Text style={[s.eyebrow,{color:colors.mutedForeground}]}>VOLUMEN OBJETIVO</Text><Text style={[s.volumeVal,{color}]}>{actual} / {target} vueltas</Text></View><View style={[s.pill,{backgroundColor:`${color}18`}]}><Ionicons name={done?'checkmark-circle':'flag-outline'} size={15} color={color}/><Text style={[s.pillTxt,{color}]}>{done?'OBJETIVO CUMPLIDO':`${Math.round(pct)}%`}</Text></View></View><View style={[s.track,{backgroundColor:colors.muted}]}><View style={[s.fill,{width:`${Math.min(100,pct)}%`,backgroundColor:color}]}/></View><Text style={[s.small,{color:colors.mutedForeground}]}>{done?'Puedes seguir registrando vueltas extra.':`Faltan ${remaining} vuelta${remaining!==1?'s':''}.`}</Text></View>}
function Coach({laps,target,ok,fail,pct,colors}:{laps:Lap[];target:number;ok:number;fail:number;pct:number;colors:ReturnType<typeof useColors>}){const recent=laps.slice(-5);return <View style={[s.panel,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={s.panelHead}><View><Text style={[s.eyebrow,{color:colors.mutedForeground}]}>OBJETIVO / VUELTA</Text><Text style={[s.volumeVal,{color:colors.primary}]}>{formatTime(target)}</Text></View><Text style={[s.small,{color:colors.mutedForeground}]}>✓ {ok} · ✗ {fail} · {Math.round(pct)}%</Text></View>{recent.length>0&&<View style={s.trend}>{recent.map(l=>{const good=isLapOnTarget(l.lapTime,target),color=good?colors.lapBest:colors.lapWorst;return <View key={l.number} style={s.trendItem}><Ionicons name={good?'checkmark-circle':'close-circle'} size={18} color={color}/><Text style={[s.tiny,{color:colors.mutedForeground}]}>V{l.number}</Text><Text style={[s.tiny,{color}]}>{l.lapTime-target>0?'+':'-'}{(Math.abs(l.lapTime-target)/1000).toFixed(2)}s</Text></View>})}</View>}</View>}
function Chip({label,value,color,colors}:any){return <View style={s.chip}><Text style={[s.chipVal,{color}]}>{value}</Text><Text style={[s.chipLbl,{color:colors.mutedForeground}]}>{label}</Text></View>}
const s=StyleSheet.create({container:{flex:1},timerZone:{alignItems:'center',paddingHorizontal:20,paddingBottom:8},meta:{fontSize:12,fontFamily:'Inter_500Medium',marginBottom:5},timer:{fontSize:56,fontFamily:'Inter_700Bold',letterSpacing:-2,fontVariant:['tabular-nums']},finished:{alignItems:'center',gap:6,paddingVertical:5},done:{fontSize:22,fontFamily:'Inter_700Bold'},sub:{fontSize:14},volumeDone:{fontSize:14,fontFamily:'Inter_700Bold'},targetBox:{width:'100%',marginTop:6,padding:9,borderRadius:12,borderWidth:1,alignItems:'center'},targetHead:{width:'100%',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{fontSize:10,fontFamily:'Inter_600SemiBold',letterSpacing:1.1},pill:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:8,paddingVertical:4,borderRadius:12},pillTxt:{fontSize:9,fontFamily:'Inter_700Bold'},lapClockBig:{fontSize:28,fontFamily:'Inter_700Bold',fontVariant:['tabular-nums']},delta:{fontSize:11,fontFamily:'Inter_600SemiBold'},lapInfo:{alignItems:'center',marginTop:6},lapClock:{fontSize:23,fontFamily:'Inter_600SemiBold'},hint:{fontSize:14,marginTop:5},panel:{marginHorizontal:14,borderRadius:12,padding:10,borderWidth:StyleSheet.hairlineWidth,marginBottom:7,gap:7},panelHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},eyebrow:{fontSize:9,fontFamily:'Inter_700Bold',letterSpacing:.8},volumeVal:{fontSize:18,fontFamily:'Inter_700Bold',fontVariant:['tabular-nums']},track:{height:6,borderRadius:3,overflow:'hidden'},fill:{height:'100%',borderRadius:3},small:{fontSize:10,fontFamily:'Inter_500Medium'},trend:{flexDirection:'row',justifyContent:'space-between',paddingTop:4},trendItem:{alignItems:'center',minWidth:48},tiny:{fontSize:8,fontFamily:'Inter_600SemiBold'},strip:{flexDirection:'row',alignItems:'center',marginHorizontal:14,borderRadius:12,padding:8,borderWidth:StyleSheet.hairlineWidth,marginBottom:7},chip:{flex:1,alignItems:'center'},chipVal:{fontSize:13,fontFamily:'Inter_600SemiBold'},chipLbl:{fontSize:9},div:{width:1,height:26},laps:{flex:1},lapsHead:{flexDirection:'row',paddingHorizontal:16,paddingVertical:7,borderBottomWidth:StyleSheet.hairlineWidth,gap:8},th:{fontSize:10,fontFamily:'Inter_600SemiBold'},btns:{paddingHorizontal:14,paddingTop:8,gap:8},bigBtn:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,paddingVertical:16,borderRadius:14},bigTxt:{fontSize:17,fontFamily:'Inter_700Bold'},action:{flexDirection:'row',gap:10},lapBtn:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,minHeight:104,borderRadius:16,borderWidth:2},stack:{gap:8},side:{width:58,height:48,borderRadius:14,alignItems:'center',justifyContent:'center'},half:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingVertical:16,borderRadius:14},actionTxt:{fontSize:16,fontFamily:'Inter_700Bold'}});
