import React from 'react';
import {StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {useColors} from '@/hooks/useColors';
import {Ionicons} from '@expo/vector-icons';
import {Session} from '@/types/training';
import {formatTime,formatDate,calculateStats} from '@/utils/calculations';
interface Props{session:Session;onPress:()=>void;}
export function SessionCard({session,onPress}:Props){const colors=useColors();const stats=calculateStats(session.laps,session.distancePerLap,session.targetLapTimeMs);const volumePct=session.targetLapCount?Math.min(100,session.laps.length/session.targetLapCount*100):0;const volumeComplete=!!session.targetLapCount&&session.laps.length>=session.targetLapCount;return <TouchableOpacity onPress={onPress} activeOpacity={0.72} style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={s.header}><View style={s.titleRow}><View style={[s.typePill,{backgroundColor:`${colors.primary}22`}]}><Text style={[s.type,{color:colors.primary}]}>{session.trainingType}</Text></View>{session.distancePerLap>0&&<Text style={[s.distance,{color:colors.mutedForeground}]}>{session.distancePerLap}m/v</Text>}</View><Ionicons name="chevron-forward" size={16} color={colors.mutedForeground}/></View><Text style={[s.meta,{color:colors.mutedForeground}]}>{formatDate(session.date)}{session.athleteName?` · ${session.athleteName}`:''}</Text><View style={s.statsRow}><Chip label="Tiempo" value={formatTime(session.totalTime)} colors={colors}/><Chip label="Vueltas" value={session.targetLapCount?`${session.laps.length}/${session.targetLapCount}`:String(session.laps.length)} colors={colors} accent={session.targetLapCount?(volumeComplete?colors.lapBest:colors.lapWorst):undefined}/>{session.targetLapCount&&<Chip label="Volumen" value={`${Math.round(volumePct)}%`} colors={colors} accent={volumeComplete?colors.lapBest:colors.lapWorst}/>} {stats.bestLap&&<Chip label="Mejor v." value={formatTime(stats.bestLap.lapTime)} colors={colors} accent={colors.lapBest}/>} {session.targetLapTimeMs&&session.laps.length>0&&<Chip label="Ritmo" value={`${Math.round(stats.targetCompliance)}%`} colors={colors} accent={stats.targetCompliance>=80?colors.lapBest:colors.primary}/>} {stats.averageSpeed>0&&<Chip label="Vel. med." value={`${stats.averageSpeed.toFixed(1)} km/h`} colors={colors}/>}</View></TouchableOpacity>}
function Chip({label,value,colors,accent}:{label:string;value:string;colors:ReturnType<typeof useColors>;accent?:string}){return <View style={s.chip}><Text style={[s.chipValue,{color:accent??colors.foreground}]}>{value}</Text><Text style={[s.chipLabel,{color:colors.mutedForeground}]}>{label}</Text></View>}
const s=StyleSheet.create({card:{borderRadius:14,padding:14,marginHorizontal:16,marginBottom:10,borderWidth:StyleSheet.hairlineWidth,gap:8},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},titleRow:{flexDirection:'row',alignItems:'center',gap:8},typePill:{paddingHorizontal:10,paddingVertical:3,borderRadius:20},type:{fontSize:13,fontFamily:'Inter_600SemiBold'},distance:{fontSize:12,fontFamily:'Inter_400Regular'},meta:{fontSize:12,fontFamily:'Inter_400Regular'},statsRow:{flexDirection:'row',gap:16,flexWrap:'wrap'},chip:{gap:1},chipValue:{fontSize:14,fontFamily:'Inter_600SemiBold',fontVariant:['tabular-nums']},chipLabel:{fontSize:10,fontFamily:'Inter_400Regular'}});
